### ISSUE TITLE
Reproduce the COCO result.

### ISSUE THREAD

**Issue by atranitell** [urbaneman/mmdetection_mobilenet#1]
Hi,

May I have known your precision on COCO datasets (mAP) by using mobilenet-v2-ssd config file.

Best

**Comment by urbaneman** [comment]
@atranitell Hi, I haven't train the model in COCO datasets. I just retrain the model in my dataset with 8 classes. The mAP is 69.5.
I sorry for can't tell you the result

**Comment by atranitell** [comment]
@urbaneman thx your reply, I have reproduced it as same as the reported result.

**Comment by zhaoxin111** [comment]
> @urbaneman thx your reply, I have reproduced it as same as the reported result.

Hi, may I ask how high precision you can get on the coco data set? the map I have reproduced was 18，which is much lower than the reported result. 

Best

**Comment by atranitell** [comment]
> > @urbaneman thx your reply, I have reproduced it as same as the reported result.
> 
> Hi, may I ask how high precision you can get on the coco data set? the map I have reproduced was 18，which is much lower than the reported result.
> 
> Best

Hi, MobileNet-v1 SSD could achieve 18.x and v2 could gain 23/24.x precision.

Best,
KJ

**Comment by zhaoxin111** [comment]
> > > @urbaneman thx your reply, I have reproduced it as same as the reported result.
> > 
> > 
> > Hi, may I ask how high precision you can get on the coco data set? the map I have reproduced was 18，which is much lower than the reported result.
> > Best
> 
> Hi, MobileNet-v1 SSD could achieve 18.x and v2 could gain 23/24.x precision.
> 
> Best,
> KJ

Nice job！Would you show some config of the MV2SSD or the ssdhead, I have try many methods to improve the precesion.This problem has bothered me for a long time.

Best
zhaoxin
