### ISSUE TITLE
would you please open source your ssdmobilenet pretrained model?

### ISSUE THREAD

**Issue by jsnoc** [urbaneman/mmdetection_mobilenet#2]
dear friend ,thanks for your open source,  i am trying to recurrent the mobilenetv2 ssd, so would you please open source your ssdmobilenetv2 pretrained model  './pretrain_model/mobilenetv2_1.0-0c6065bc.pth',  need your help please

**Comment by urbaneman** [comment]
@jsnoc Sorry for reply so late. 
I download the MobileNet-V2 pre-train model from d-li14's work. This is the repo [d-li14/mobilenetv2.pytorch](https://github.com/d-li14/mobilenetv2.pytorch),
The pre-train model is [mobilenetv2_1.0-0c6065bc.pth](https://github.com/d-li14/mobilenetv2.pytorch/blob/master/pretrained/mobilenetv2_1.0-0c6065bc.pth).
Enjoy it!

**Comment by jsnoc** [comment]
awesome！！！
